config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "categories#index"

  resources :categories, only: [:index, :new, :create] do
    resources :expenses, only: [:new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  include ImageUploader::Attachment(:icon)

  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses, dependent: :destroy

  # validations
  validates :name, presence: true

  def format_date(time_with_zone)
    time_with_zone.strftime('%d %b %Y')
  end
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  validates :expense, uniqueness: { scope: :category, message: 'already exists in this category' }

  # associations
  belongs_to :expense
  belongs_to :category
end

app/models/expense.rb
class Expense < ApplicationRecord
  # associations
  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy
  has_many :categories, through: :category_expenses, dependent: :destroy

  # validations
  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def format_date(time_with_zone)
    time_with_zone.strftime('%d %b %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validations
  validates :name, presence: true
  validates :email, presence: true

  # associations
  has_many :categories, foreign_key: :author_id, dependent: :destroy
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # to whitelist additional input fields other than what devise has by default
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_category, only: [:show]

  def index
    @cats = Category.all.order(created_at: :desc).includes(:expenses)
  end

  def new
    @new_category = Category.new
  end

  def create
    @category = Category.new(author_id: current_user.id, **category_params)

    if @category.save
      flash[:notice] = 'Category added successfully'
      redirect_to categories_path
    else
      flash.now[:alert] = 'Category could not be saved!'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[index create new]

  def index
    @expenses = @category.expenses.order(created_at: :desc)
    @expenses_sum = @expenses.sum(:amount)
  end

  def new
    @new_expense = Expense.new
    @categories = Category.all
  end

  def create
    @expense = Expense.new(author_id: current_user.id, **expense_params)

    if @expense.save
      CategoryExpense.create!(category_id: @category.id, expense_id: @expense.id)
      flash[:notice] = 'Transaction recorded successfully'
      redirect_to category_expenses_path(@category)
    else
      flash.now[:alert] = 'Transaction could not be saved'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end

  def set_category
    @category = Category.find(params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<%= render 'shared/nav', title: 'Categories' %>

<div class="container">
  <%= render 'shared/notification_box' %>
  <div class="mb-5">
    <ul class='item'>
      <% if @cats.empty? %>
      <li><i class="text-center">No Categories available</i></li>
      <% else %>
      <% @cats.each_with_index do |cat, i| %>
        <li class='category-item'>
          <a href="/categories/<%= cat.id %>/expenses" class="card p-3 mb-3">
            <div class="row">
              <div class="col-4">
                <%= (image_tag cat.icon_url, class: 'img-fluid') if cat.icon  %>
              </div>

              <div class="col-5">
                <div class="text-muted text-bold d-flex flex-column gap-3 justify-content-center pt-4">
                  <h3 class="category-name fs-4"><%= cat.name %></h3>
                  <p class="date-created fs-4"><%= cat.format_date(cat.created_at) %></p>
                </div>
              </div>

              <div class="col-3">
                <div class="text-bold text-black pt-4">
                  <h3 class="fs-4"> <small><span class="text-muted">spent</span>: <%= "$" + cat.expenses.sum(:amount).to_s + "0"  %></small></h3>
                </div>
              </div>
            </div>
          </a>
        </li>
      <% end %>
      <% end %>
    </ul>

    <div class="d-grid">
      <%= link_to new_category_path, class: "btn btn-outline-primary d-flex justify-content-center align-items-center" do %>
        <svg class="svg-icon text-bold fs-4" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15"></path>
        </svg>
        <span class="text-bold fs-4">Add Category</span>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'shared/nav', title: 'Category'%>
<div class="container">
  <%= render 'shared/notification_box'%>
  <div class="form-section d-flex justify-content-center align-items-center mb-3">
    <%= form_with model: @new_category, html: { class:'bs' }, url: categories_path do |f| %>
      <div class='text-center px-4 py-2 gap-2 bg-dark text-white d-flex justify-content-center align-items-center'>
        <svg class="svg-icon" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
        </svg>
        <div class='fs-4'>Add Category</div>
      </div>

      <div class='px-4 pb-4'>
        <div class="field mb-3">
          <%= f.label :name, class:'form-label' %><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class:'form-control', required: true %>
        </div>

        <div class="field mb-3">
          <%= f.label :icon, class:'form-label' %><br />
          <%= f.file_field :icon, autocomplete: "icon", class:'form-control', required: true %>
        </div>

        <div class="actions d-grid mb-3">
          <%= f.submit "Save", class: 'btn btn-outline-primary' %>
        </div>

        <div class="d-flex justify-content-center back-btn">
          <%= link_to "< Back", "/categories", class:'text-center' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/expenses/index.html.erb
<%= render 'shared/nav', title: 'Transactions' %>

<div class="container">
  <%= render 'shared/notification_box' %>

  <div class="mb-5">  
    <div class="bs mb-3">
      <div class="d-flex justify-content-between align-items-center px-2">
        <%= link_to '< Back', categories_path %>

        <h3 class="text-center self-align-center flex-grow-1">
          Total: $<%= @expenses_sum.to_s + "0" %>
        </h3>
      </div>
    </div>


    <ul class='item'>
      <% if @expenses.empty? %>
      <li class="text-center card p-4"><i>No Transactions available</i></li>
      <% else %>
      <% @expenses.each_with_index do |t, i| %>
        <li class='category-item'>
          <div class="card p-3 mb-3">
            <div class="row">
              <div class="col-4">
                <%= (image_tag @category.icon_url, class: 'img-fluid') if @category.icon %>
              </div>

              <div class="col-5">
                <div class="text-muted text-bold d-flex flex-column gap-3 justify-content-center pt-4">
                  <h3 class="category-name fs-4"><%= t.name %></h3>
                  <p class="date-created fs-4"><%= t.format_date(t.created_at) %></p>
                </div>
              </div>

              <div class="col-3">
                <div class="text-bold text-black pt-4">
                  <h4 class="fs-5"><%= "$" + t.amount.to_s + "0"  %></h4>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
      <% end %>
    </ul>

    <div class="d-grid">
      <%= link_to new_category_expense_path(@category), class: "btn btn-outline-success d-flex justify-content-center align-items-center" do %>
        <svg class="svg-icon text-bold fs-4" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15"></path>
        </svg>
        <span class="text-bold fs-4">Add Transaction</span>
      <% end %>
    </div>
  </div>
</div>

app/views/expenses/new.html.erb
<%= render 'shared/nav', title: 'Transaction' %>

<div class="container">
  <%= render 'shared/notification_box' %>

  <div class="form-section d-flex justify-content-center align-items-center mb-3">
    <%= form_with model: @new_expense, html: { class:'bs' }, url: category_expenses_path do |f| %>
      <div class='text-center px-4 py-2 gap-2 bg-dark text-white d-flex justify-content-center align-items-center'>
        <svg class="svg-icon" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
        </svg>
        <div class='fs-4'>Add Transaction</div>
      </div>

      <div class='px-4 pb-4'>
        <div class="field mb-3">
          <%= f.label :name, class:'form-label' %><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class:'form-control', required: true %>
        </div>

        <div class="field mb-3">
          <%= f.label :amount, class:'form-label' %><br />
          <%= f.number_field :amount, autocomplete: "amount", class:'form-control', required: true, step: "0.01" %>
        </div>

        <div class="actions d-grid mb-3">
          <%= f.submit "Save", class: 'btn btn-outline-primary' %>
        </div>

        <div class="d-flex justify-content-center back-btn">
          <%= link_to "< Back", "/categories/#{@category.id}/expenses", class:'text-center' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-start text-bg-dark text-muted" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">BudgetTracker</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <svg class='nav-icon' fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z"></path>
              </svg>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <% if user_signed_in? %>
                <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              <% else %>
                <li> <%= link_to 'Sign In', new_user_session_path, class: 'dropdown-item' %></li>
                <li> <%= link_to 'Sign Up', new_user_registration_path, class: 'dropdown-item' %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>

    <div class="navbar-brand mx-auto fs-3"><%= title %></div>

    <div class="input-group me-auto">
        <i class="bi bi-search"></i>
    </div>
  </div>
</nav>

app/views/shared/_notification_box.html.erb
    <div class='notification-box container'>
      <% if alert %>
        <div class='d-flex justify-content-center alert alert-warning alert-dismissible fade show role'>
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if notice %>
        <div class='d-flex justify-content-center alert alert-info alert-dismissible fade show role'>
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </div>